### This is the Terraform-generated dev-build.yml workflow for the         ###
### s3-bagit-validator-stage app repository. If this is a Lambda repo,     ###
### uncomment the FUNCTION line at the end of the document. If the         ###
### container requires any additional pre-build commands, uncomment and    ###
### the PREBUILD line at the end of the document.                          ###
name: Stage Container Build and Deploy

# checkov:skip=CKV2_GHA_1:The shared workflow contains the permissions constraints
# NOTE: The above checkov skip command doesn't actually work and this workflow
#       will always show a checkov warning.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy-us-east-1:
    name: Stage Container Deploy
    uses: mitlibraries/.github/.github/workflows/ecr-shared-deploy-stage.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "s3-bagit-validator-gha-stage"
      ECR: "s3-bagit-validator-stage"
      FUNCTION: "s3-bagit-validator-stage"
      # PREBUILD: 

  deploy-us-west-2:
    name: Stage Container Deploy us-west-2
    uses: mitlibraries/.github/.github/workflows/ecr-shared-deploy-stage.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-west-2"
      GHA_ROLE: "s3-bagit-validator-gha-stage"
      ECR: "s3-bagit-validator-stage"
      FUNCTION: "s3-bagit-validator-stage"
      # PREBUILD: 
